package com.Studio;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/***
 * @author Connor Hunter        connh321@gmail.com
 *
 * Where SQL Queries are written and generated by JpaRepository for accessing Studio information.
 */
@Repository
public interface StudioRepository extends JpaRepository<StudioModel, Long> {

}
