version: "3.8"

services:

  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: movies
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./data/db:/var/lib/pgadmin
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    links:
      - postgres
      - pgadmin

volumes:
  postgres:
  pgadmin: