package com.CastMember;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/***
 * @author Connor Hunter        connh321@gmail.com
 *
 * Where SQL Queries are written and generated by JpaRepository for accessing CastMember information.
 */
@Repository
public interface CastMemberRepository extends JpaRepository<CastMemberModel, Long> {
}
