package com.Director;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/***
 * @author Connor Hunter        connh321@gmail.com
 *
 * Where SQL Queries are written and generated by JpaRepository for accessing Director information.
 */
@Repository
public interface DirectorRepository extends JpaRepository<DirectorModel, Long> {
}
