package com.Movie;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/***
 * @author Connor Hunter        connh321@gmail.com
 *
 * Where SQL Queries are written and generated by JpaRepository for accessing Movie information.
 */
@Repository
public interface MovieRepository extends JpaRepository<MovieModel, Long> {
}
